-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : mer. 21 oct. 2020 à 18:53
-- Version du serveur :  10.3.24-MariaDB
-- Version de PHP : 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `eran7268_slipix`
--

-- --------------------------------------------------------

--
-- Structure de la table `champions`
--

CREATE TABLE `champions` (
  `id` int(255) UNSIGNED NOT NULL COMMENT 'L''identifiant du champion',
  `name` varchar(50) CHARACTER SET utf8mb4 NOT NULL,
  `pictureHead` varchar(50) NOT NULL,
  `pictureChampion` varchar(30) NOT NULL,
  `history` varchar(1000) NOT NULL,
  `competence_id` int(255) UNSIGNED NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'La date de création du champion',
  `updated_at` timestamp NULL DEFAULT NULL COMMENT 'La date de la dernière mise à jour du champion'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `champions`
--

INSERT INTO `champions` (`id`, `name`, `pictureHead`, `pictureChampion`, `history`, `competence_id`, `created_at`, `updated_at`) VALUES
(1, 'zac', 'zac/zac-head.jpg', 'zac/zac.jpg', '\"Zac est le produit d\'une fuite toxique qui, dégoulinant par une veine techno-chimique, se transforma en bassin dans une profonde caverne du Puisard de Zaun. En dépit de ses humbles origines, Zac a évolué pour passer du stade de dépôt primordial à celui d\'être pensant qui se faufile dans les canalisations de la ville. De temps en temps, il émerge pour aider ceux qui ne s\'en sortent pas seuls ou pour reconstruire les infrastructures en mauvais état de Zaun.\"', 1, '2020-06-07 19:17:09', NULL),
(2, 'olaf', 'olaf/olaf_head.jpg', 'olaf/olaf.jpg', 'Olaf, avec sa hache et son extraordinaire force de destruction, ne souhaite que mourir au combat. Venu de l\'âpre péninsule freljordienne de Lokfar, il a été choqué par une prophétie qui lui prédisait une mort paisible : dans l\'esprit de son peuple, une ignoble fin de lâche. Cherchant la mort et animé par la rage, il ravage une région après l\'autre, éliminant des hordes de grands guerriers et de bêtes légendaires dans sa recherche d\'un ennemi capable de l\'arrêter. Aujourd\'hui un brutal combattant de la Griffe hivernale, il espère mourir glorieusement dans les grandes guerres à venir.', 2, '2020-06-11 14:12:27', NULL),
(3, 'ekko', 'ekko/ekko_head.jpg', 'ekko/ekko.jpg', 'Jeune prodige des rues mal famées de Zaun, Ekko manipule le temps pour renverser toute situation dangereuse à son avantage. En utilisant sa propre invention, la clepsydre-zéro, il explore les différents possibles de la réalité pour surmonter les difficultés. Bien qu\'il aime sa liberté, lorsque ses amis sont menacés, il est prêt à tout pour les défendre. Pour quiconque ne le connaît pas, Ekko semble toujours accomplir l\'impossible, et du premier coup.', 3, '2020-06-13 11:30:04', NULL),
(4, 'lee-sin', 'leeSin/leeSin_head.jpg', 'leeSin/lee_sin.jpg', 'Maître des antiques arts martiaux d\'Ionia, Lee Sin est un combattant dévoué à de nobles principes qui canalise l\'esprit du dragon pour affronter tous les défis. Bien qu\'il ait perdu la vue il y a bien des années, le moine-guerrier a dédié sa vie à la protection de sa terre natale contre tous ceux qui voudraient en déstabiliser l\'équilibre spirituel. Les ennemis qui sous-estiment son apparence méditative auront peu de temps pour le regretter, face à ses poings de feu et à ses coups de pied flamboyants.', 4, '2020-06-21 12:51:18', NULL),
(5, 'gragas', 'gragas/gragas_head.jpg', 'gragas/gragas.jpg', 'Aussi imposant que jovial, Gragas est un brasseur à l\'impressionnante carrure qui cherche la recette de la bière parfaite. Venu d\'on ne sait où, il continue de chercher les ingrédients les plus rares dans les terres vierges de Freljord, essayant toutes les variations de bière au cours de son périple. Souvent ivre et toujours impulsif, il est légendaire pour ses rixes, qui finissent souvent en fêtes nocturnes préjudiciables au mobilier urbain. Toute apparition de Gragas annonce beuverie et destruction. Dans cet ordre.', 5, '2020-06-21 14:05:09', NULL),
(6, 'hecarim', 'hecarim/hecarim_head.jpg', 'hecarim/hecarim.jpg', 'Fusion spectrale de l\'homme et de la bête, Hecarim est condamné à pourchasser les âmes des vivants pour l\'éternité. Lorsque les ombres ont envahi les Îles bénies, ce fier chevalier et sa horde de cavaliers ont été anéantis par les énergies destructrices de la Ruine. À présent, quand la Brume noire s\'étend sur Runeterra, il mène la charge et se plaît à massacrer et écraser ses ennemis sous ses lourds sabots.', 6, '2020-07-25 20:19:19', NULL),
(7, 'volibear', 'volibear/volibear_head.jpg', 'volibear/volibear.jpg', 'Pour ceux qui le vénèrent encore, Volibear est l\'incarnation de la tempête. Destructeur, sauvage et déterminé, il existait bien avant que les mortels n\'arpentent la toundra de Freljord ; désormais, il défend férocement les terres qu\'il a créées avec sa famille de demi-dieux. Habité d\'une haine profonde envers la civilisation et la faiblesse qu\'elle a engendrée, il se bat à coups de crocs et de griffes pour restaurer les traditions d\'autrefois, celles du temps où la terre était sauvage et où le sang coulait librement.', 7, '2020-07-25 22:18:28', NULL),
(8, 'pantheon', 'pantheon/pantheon_head.jpg', 'pantheon/pantheon.jpg', 'Autrefois l\'hôte réticent de la Manifestation de la Guerre, Atreus a survécu à la mort de la puissance céleste qui l\'habitait, refusant de succomber au coup qui arracha les étoiles mêmes des cieux. Avec le temps, il apprit à accepter le pouvoir de sa mortalité, et la résistance bornée qui y est associée. Atreus s\'oppose désormais aux entités divines en tant que Pantheon, ressuscité parmi les mortels, et manie les armes de la Manifestation animées par sa volonté inébranlable sur le champ de bataille.', 8, '2020-07-26 12:21:46', NULL),
(9, 'rumble', 'rumble/rumble_head.jpg', 'rumble/rumble.jpg', 'Rumble est un jeune inventeur soupe au lait. Ne disposant que de ses deux mains et d\'une pile de ferraille, le yordle au tempérament de feu se fabriqua une colossale armure mécanique, dotée d\'un arsenal de harpons électrifiés et de roquettes incendiaires. Si certains pouffent devant ses créations sorties tout droit d\'une décharge, Rumble n\'en a que faire : après tout, c\'est lui qui est doté d\'un lance-flammes.', 9, '2020-07-26 12:45:45', NULL),
(10, 'camille', 'camille/camille_head.jpg', 'camille/camille.jpg', 'Transformée en arme pour agir en dehors des limites de la loi, Camille est le principal défenseur du clan Ferros, un agent élégant et supérieur qui contribue à faire fonctionner correctement la machine de Piltover et son ombre zaunienne. Son adaptabilité et sa précision sont si élevées qu\'une technique maladroite est pour elle une honte qu\'il convient d\'éradiquer. Dotée d\'un esprit aussi affûté que ses lames, Camille recherche la supériorité par l\'optimisation Hextech du corps, au point que certains se demandent si elle n\'est pas désormais plus machine que femme.', 10, '2020-07-26 13:04:37', NULL),
(11, 'mordekaiser', 'mordekaiser/mordekaiser_head.jpg', 'mordekaiser/mordekaiser.jpg', 'Deux fois abattu et trois fois né, Mordekaiser est un chef de guerre brutal venu d\'un lointain passé. Il utilise ses pouvoirs nécromantiques pour lier les âmes à une éternité de servitude. Il n\'y a plus guère de gens pour se souvenir de ses anciennes conquêtes ou pour connaître l\'étendue de ses vrais pouvoirs. Pourtant, certaines âmes antiques en ont gardé la mémoire et craignent le jour où il prétendra de nouveau régner sur les vivants et les morts.', 11, '2020-07-26 13:39:53', NULL),
(12, 'gnar', 'gnar/gnar_head.jpg', 'gnar/gnar.jpg', 'Gnar est un yordle primitif dont les manières joyeuses peuvent soudain faire place à une colère irrationnelle. Il se transforme alors en une bête colossale portée à la destruction. Gelé dans de la glace pure pendant des millénaires, la curieuse créature s\'est libérée de sa prison. Aujourd\'hui, il parcourt avec enthousiasme un monde qu\'il trouve exotique et merveilleux. Enchanté par le danger, Gnar lance à ses ennemis tout ce qu\'il trouve, qu\'il s\'agisse de son boomerang en croc ou d\'un bâtiment proche.', 12, '2020-07-26 14:05:36', NULL),
(13, 'kled', 'kled/kled_head.jpg', 'kled/kled.jpg', 'Guerrier aussi intrépide que grincheux, Kled est la plus pure incarnation de la fureur de Noxus. C\'est un symbole que les soldats de l\'empire adorent, dont les officiers se méfient et que la noblesse déteste. Beaucoup affirment que Kled a participé à toutes les campagnes des légions, qu\'il a obtenu toutes les distinctions militaires et qu\'il n\'a jamais reculé devant un combat. Si la véracité des détails est souvent douteuse, une partie de sa légende reste indéniable : quand il charge sur le dos de Skaarl, sa monture un peu froussarde, Kled se bat pour protéger ce qui lui appartient... et s\'emparer de tout le reste !', 14, '2020-07-26 15:04:54', NULL),
(14, 'vladimir', 'vladimir/vladimir_head.jpg', 'vladimir/vladimir.jpg', 'Assoiffé de sang humain, Vladimir influe sur la politique de Noxus depuis les premiers jours de l\'empire. En plus d\'allonger surnaturellement sa vie, sa maîtrise de l\'hémomancie lui permet de contrôler les esprits et les corps des autres aussi aisément que les siens. Dans les flamboyants salons de l\'aristocratie noxienne, cela lui a permis de créer autour de lui un culte de la personnalité. Cependant, dans les bas-fonds, il saigne littéralement ses ennemis à blanc.', 15, '2020-07-26 18:31:30', NULL),
(15, 'lux', 'lux/lux_head.jpg', 'lux/lux.jpg', 'Luxanna Crownguard est originaire de Demacia, un royaume isolationniste où la magie inspire la peur et la méfiance. Capable de plier la lumière à sa volonté, elle a grandi dans la crainte d\'être un jour exilée et a été contrainte de dissimuler son pouvoir pour préserver l\'honneur de sa famille. Cependant, l\'optimisme et la ténacité de Lux l\'ont conduite à accepter ses talents uniques, et elle les emploie désormais secrètement pour le bénéfice de sa patrie.', 16, '2020-07-29 17:11:44', NULL),
(16, 'zed', 'zed/zed_head.jpg', 'zed/zed.jpg', 'L\'impitoyable Zed est le maître de l\'Ordre de l\'ombre, une organisation qu\'il a créée dans l\'intention de militariser la tradition des arts martiaux d\'Ionia et de chasser enfin les envahisseurs noxiens. Pendant la guerre, le désespoir le conduisit à déchaîner la Forme secrète de l\'ombre, un puissant esprit maléfique aussi dangereux que corrompu. Si Zed maîtrise ces techniques interdites, c\'est pour détruire tout ce qu\'il considère comme une menace contre sa nation ou son ordre.', 17, '2020-07-31 18:09:47', NULL),
(17, 'leblanc', 'leblanc/leblanc_head.jpg', 'leblanc/leblanc.jpg', 'Mystérieuse, même aux yeux des autres membres de la Rose noire, LeBlanc n\'est que l\'un des nombreux noms de la femme pâle qui manipule le destin de Noxus depuis ses premiers jours. Utilisant sa magie pour se cloner, elle peut être partout, devant tout le monde, et même à plusieurs endroits en même temps. Les objectifs que poursuit LeBlanc, de même que sa véritable identité, sont à l\'image de ses complots : totalement insaisissables.', 18, '2020-07-31 19:00:12', NULL),
(18, 'ryze', 'ryze/ryze_head.jpg', 'ryze/ryze.jpg', 'Largement considéré comme l\'un des plus puissants sorciers de Runeterra, Ryze est un archimage endurci par les ans qui porte un fardeau incommensurable sur ses épaules. Armé d\'une constitution à toute épreuve et d\'un vaste arsenal de connaissances mystiques, il consacre sa vie à rassembler les Runes telluriques, les fragments de magie brute qui ont jadis servi à façonner le monde. Ryze doit récupérer ces reliques avant qu\'elles ne tombent entre de mauvaises mains, car il sait quel genre d\'horreurs elles pourraient déchaîner sur Runeterra.', 19, '2020-07-31 19:17:42', NULL),
(19, 'ahri', 'ahri/ahri_head.jpg', 'ahri/ahri.jpg', 'Dotée d\'un lien inné avec le pouvoir naturel de Runeterra, Ahri est une Vastaya capable de modeler la magie pour en faire des orbes d\'énergie pure. Elle aime plus que tout jouer avec ses proies en manipulant leurs émotions avant de dévorer leur essence vitale. En dépit de sa nature de prédateur, Ahri n\'est pas sans empathie, car chaque âme qu\'elle absorbe l\'emplit de fragments de ses souvenirs.', 20, '2020-07-31 19:41:55', NULL),
(20, 'yasuo', 'yasuo/yasuo_head.jpg', 'yasuo/yasuo.jpg', 'L\'Ionien Yasuo est un épéiste agile et résolu, capable de déchaîner contre ses ennemis la puissance de l\'air. Alors qu\'il était encore un jeune homme fier, il fut accusé à tort d\'avoir assassiné son maître. Incapable de prouver son innocence, il dut fuir et fut finalement contraint de tuer son frère pour se défendre. Même après la découverte du véritable meurtrier de son maître, Yasuo ne parvint pas à faire la paix avec sa conscience. Il erre désormais dans son pays natal, et seul le vent guide sa lame.', 21, '2020-07-31 21:15:38', NULL),
(21, 'evelynn', 'evelynn/evelynn_head.jpg', 'evelynn/evelynn.jpg', 'Dans les sombres failles de Runeterra, le démon nommé Evelynn cherche sa prochaine victime. Elle attire sa proie en se faisant passer pour une femme voluptueuse, et dès que sa cible succombe à ses charmes, Evelynn révèle sa véritable nature. Elle inflige alors à sa victime des tourments indicibles et se repaît de sa douleur. Pour un démon, ce ne sont que des plaisirs innocents. Aux yeux du reste de Runeterra, ce sont des contes terrifiants, qui rappellent les dangers du désir et de la luxure.', 22, '2020-08-01 18:36:38', NULL),
(22, 'shaco', 'shaco/shaco_head.jpg', 'shaco/shaco.jpg', 'Fabriqué il y a longtemps pour servir de jouet à un prince qui se sentait seul, Shaco est une marionnette enchantée qui se repaît désormais de meurtres et de chaos. Corrompu par la magie noire et la perte de sa chère mission, le pantin autrefois gentil ne se réjouit plus que du malheur des âmes qu\'il tourmente. Il utilise ses jouets et ses mauvais tours pour répandre la mort et le sang, ce qui le fait follement rire. Tous ceux qui, la nuit venue, entendent un odieux ricanement savent qu\'ils sont la prochaine cible du Bouffon des ténèbres.', 23, '2020-08-01 18:56:03', NULL),
(23, 'xinZhao', 'xinZhao/xin_head.jpg', 'xinZhao/xinZhao.jpg', 'Xin Zhao est un guerrier résolu qui sert fidèlement la dynastie régnante des Lightshield. Naguère condamné à se battre dans les arènes de combat de Noxus, il survécut à d\'innombrables rencontres de gladiateurs. Mais après avoir été libéré par les forces de Demacia, il jura allégeance à ses braves libérateurs. Armé de sa lance à trois pointes, Xin Zhao combat désormais pour son royaume, défiant ses ennemis avec audace, quelles que soient ses chances de succès.', 24, '2020-08-01 19:10:45', NULL),
(24, 'aatrox', 'aatrox/aatrox_head.jpg', 'aatrox/aatrox.jpg', 'Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des siècles d\'emprisonnement, Aatrox fut le premier à retrouver sa liberté, en corrompant et transformant les mortels assez stupides pour tenter de s\'emparer de l\'arme magique qui contenait son essence. Désormais en possession d\'un corps qu\'il a approximativement transformé pour rappeler son ancienne forme, il arpente Runeterra en cherchant à assouvir sa vengeance apocalyptique.', 13, '2020-08-01 19:20:15', NULL),
(25, 'darius', 'darius/darius_head.jpg', 'darius/darius.jpg', 'Il n\'est pas de plus grand symbole de la puissance de Noxus que Darius, le commandant le plus craint et le plus endurci de la nation. D\'origine modeste, celui qui s\'est élevé jusqu\'à devenir la Main de Noxus pourfend aujourd\'hui les ennemis de l\'empire, dont certains sont eux-mêmes des Noxiens. Il ne doute jamais de la justesse de sa cause et ne montre pas la moindre hésitation lorsque sa hache est levée. Ceux qui s\'opposent au chef de la Légion Trifarian ne doivent s\'attendre à aucune pitié.', 25, '2020-08-01 19:33:01', NULL),
(26, 'sett', 'sett/sett_head.jpg', 'sett/sett.jpg', 'Sett s\'est imposé en tant que chef du monde criminel florissant d\'Ionia après la guerre contre Noxus. Bien qu\'il ait fait ses débuts de manière modeste dans les arènes de combat de Navori, il s\'est rapidement fait une réputation pour sa force sauvage et sa capacité à encaisser tous les coups sans broncher. Après s\'être battu pour se faire une place parmi les combattants locaux, Sett s\'est hissé au sommet à la force de ses poings pour finalement prendre le contrôle des arènes dans lesquelles il se battait autrefois.', 26, '2020-08-01 19:48:33', NULL),
(27, 'katarina', 'katarina/katarina_head.jpg', 'katarina/katarina.jpg', 'Aussi prompte dans ses décisions qu\'elle est meurtrière en combat, Katarina figure parmi les assassins les plus prestigieux de Noxus. Fille aînée du légendaire général Du Couteau, elle révéla bien vite ses talents en éliminant ses ennemis avec la plus grande des discrétions. Son ambition était telle qu\'elle n\'hésitait pas à traquer des cibles solidement gardées, au risque de mettre ses alliés en danger. Quelle que fût la mission, elle n\'hésitait jamais à remplir son devoir dans un tourbillon de lames acérées.', 27, '2020-08-01 22:53:25', NULL),
(28, 'akali', 'akali/akali_head.jpg', 'akali/akali.jpg', 'Ayant abandonné l\'Ordre Kinkou et le titre de Poing de l\'ombre, Akali combat aujourd\'hui seule, prête à devenir l\'arme mortelle dont son peuple a besoin. Bien qu\'elle n\'oublie rien de tout ce que son maître Shen lui a enseigné, elle a juré de défendre Ionia contre ses ennemis, une élimination après l\'autre. Akali tue sans faire de bruit, mais son message est fort et clair : craignez l\'assassin sans maître.', 28, '2020-08-01 23:32:43', NULL),
(29, 'orianna', 'orianna/orianna_head.jpg', 'orianna/orianna.jpg', 'Autrefois une jeune fille curieuse, de chair et d\'os, Orianna est aujourd\'hui une merveille de technologie entièrement mécanisée. Elle est tombée gravement malade à la suite d\'un accident dans les quartiers inférieurs de Zaun, et son corps défaillant a été remplacé petit à petit par des prothèses perfectionnées. Accompagnée par une sphère extraordinaire qu\'elle a elle-même créée pour lui servir de compagnon et de protectrice, Orianna est désormais libre d\'explorer la merveilleuse ville de Piltover et ce qui se trouve au-delà.', 29, '2020-08-02 20:29:27', NULL),
(30, 'galio', 'galio/galio_head.jpg', 'galio/galio.jpg', 'Près de la cité étincelante de Demacia, le colosse de pierre Galio monte une garde attentive. Érigé comme un rempart contre les mages ennemis, il reste souvent immobile pendant des décennies, jusqu\'à ce que l\'apparition de puissants flux magiques le ramène à la vie. Une fois éveillé, Galio profite de chaque seconde d\'existence ; il s\'enivre des frissons du combat et de l\'honneur trop rare de défendre ses compatriotes. Mais ses triomphes ont toujours un arrière-goût amer, car la magie qu\'il éradique est également la sève qui le fait vivre, et chaque victoire le renvoie au sommeil.', 30, '2020-08-02 20:42:19', NULL),
(31, 'zoe', 'zoe/zoe_head.jpg', 'zoe/zoe.jpg', 'Incarnation de l\'espièglerie, de l\'imagination et de l\'inconstance, Zoé est une messagère cosmique de Targon, annonciatrice des grands événements qui chamboulent les mondes. Sa simple présence distord les règles mathématiques qui gouvernent dans l\'ombre les réalités et, sans pour autant le vouloir, peut même provoquer des cataclysmes. Cela explique peut-être la nonchalance désinvolte avec laquelle Zoé traite ses tâches, préférant consacrer le plus clair de son temps à s\'amuser, à jouer des tours aux mortels, bref, à faire tout ce qui lui plaît. Une rencontre avec Zoé peut se révéler joyeuse et porteuse d\'optimisme, mais ce n\'est souvent qu\'une apparence, cachant une vérité extrêmement dangereuse.', 31, '2020-08-02 20:57:16', NULL),
(32, 'annie', 'annie/annie_head.jpg', 'annie/annie.jpg', 'Dangereuse, incroyablement précoce, Annie est une enfant mage dotée d\'extraordinaires pouvoirs de pyrokinésie. Même à l\'ombre des montagnes du nord de Noxus, sa magie est un cas unique. Son affinité naturelle avec le feu se manifesta dès sa prime enfance à travers des explosions émotionnelles imprévisibles, même si elle apprit rapidement à contrôler ces éclats. Parmi ses jeux favoris, elle aime invoquer son bien-aimé ours en peluche, Tibbers, sous la forme d\'un protecteur enflammé. Perdue dans l\'innocence perpétuelle de l\'enfance, Annie sautille dans les forêts obscures, à la recherche de quelqu\'un avec qui jouer.', 32, '2020-08-02 21:06:42', NULL),
(33, 'twisted-fate', 'twistedFate/twistedFate_head.png', 'twistedFate/twistedFate.jpg', 'Twisted Fate est un virtuose des cartes à la réputation ambiguë qui a parcouru le monde entier pour l\'éblouir de son charme et de ses talents, s\'attirant l\'admiration et la haine des riches comme des pigeons. Il prend rarement les choses au sérieux, salue chaque nouveau jour avec un sourire moqueur et insouciant. Twisted a toujours un atout dans sa manche, au propre comme au figuré.', 33, '2020-08-09 17:57:39', NULL),
(34, 'kassadin', 'kassadin/kassadin_head.png', 'kassadin/kassadin.jpg', 'Kassadin se fraye un chemin brûlant dans les lieux les plus sombres du monde ; il sait que ses jours sont comptés. Guide et aventurier shurimien accompli, il avait choisi de fonder une famille parmi les tribus pacifiques du sud, jusqu\'au jour où son village fut ravagé par le Néant. Il jura de se venger et s\'arma de reliques arcaniques qu\'il combina à l\'aide de technologies interdites. Enfin, Kassadin se dirigea vers les ruines d\'Icathia à la recherche du prophète autoproclamé, Malzahar, prêt à affronter les monstres du Néant.', 34, '2020-08-09 18:15:55', NULL),
(35, 'veigar', 'veigar/veigar_head.png', 'veigar/veigar.jpg', 'Maître enthousiaste de la magie noire, Veigar s\'est approprié des pouvoirs que peu de mortels osent approcher. Habitant de Bandle à l\'esprit libre, il veut repousser les limites de la magie yordle et se tourner vers les textes arcaniques qui sont restés cachés des millénaires. Fasciné jusqu\'à l\'obstination par les mystères de l\'univers, Veigar est souvent sous-estimé par les gens qui l\'entourent. Bien qu\'il se croie fondamentalement maléfique, il possède une moralité qui le mène à s\'interroger sur ses motivations.', 35, '2020-08-09 18:26:45', NULL),
(36, 'corki', 'corki/corki_head.png', 'corki/corki.jpg', 'Il y a deux choses que Corki, le pilote yordle, aime plus que tout au monde : les sensations de vol et sa fantastique moustache... mais pas nécessairement dans cet ordre. Après avoir quitté Bandle, il s\'installa à Piltover, où il tomba amoureux des merveilleuses machines qu\'il y trouva. Il consacra tout son temps au développement d\'engins volants, tout en menant une unité de défense aérienne composée de pilotes aguerris : les Serpents volants. Serein même sous le feu ennemi, Corki patrouille dans l\'espace aérien de sa patrie d\'adoption, et il ne rencontre jamais le moindre problème qu\'un bon gros missile ne puisse résoudre.', 36, '2020-08-10 08:57:31', NULL),
(37, 'fizz', 'fizz/fizz_head.jpg', 'fizz/fizz.jpg', 'Fizz est un yordle amphibie qui vit dans les récifs qui entourent Bilgewater. Il essaie souvent de récupérer et de rendre les tributs que lancent dans l\'océan les capitaines superstitieux, mais même le plus dessalé des marins n\'est pas assez arrogant pour essayer de le tromper. On raconte bien des histoires sur ceux qui ont sous-estimé son humeur changeante... Souvent confondu avec un esprit océanique capricieux, il semble capable de commander aux créatures des profondeurs et n\'aime rien tant que confondre alliés comme ennemis.', 37, '2020-08-10 16:09:31', NULL),
(38, 'yone', 'yone/yone_head.jpg', 'yone/yone.jpg', 'Au cours de sa vie, Yone fut le demi-frère de Yasuo et un disciple renommé de l\'école d\'armes de son village. Mais après avoir été tué par son propre frère, il se retrouva hanté par une entité malveillante dans le royaume spirituel. Il dut la tuer avec sa propre épée. Désormais maudit et forcé de porter le masque de l\'azakana, Yone chasse inlassablement ces créatures démoniaques afin de comprendre ce qu\'il est devenu.', 38, '2020-09-07 18:41:12', NULL);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `champions`
--
ALTER TABLE `champions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `competence_id` (`competence_id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `champions`
--
ALTER TABLE `champions`
  MODIFY `id` int(255) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L''identifiant du champion', AUTO_INCREMENT=39;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `champions`
--
ALTER TABLE `champions`
  ADD CONSTRAINT `champions_ibfk_1` FOREIGN KEY (`competence_id`) REFERENCES `competences` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
