-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : mer. 21 oct. 2020 à 18:55
-- Version du serveur :  10.3.24-MariaDB
-- Version de PHP : 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `eran7268_slipix`
--

-- --------------------------------------------------------

--
-- Structure de la table `competences`
--

CREATE TABLE `competences` (
  `id` int(255) UNSIGNED NOT NULL,
  `sort_passif_name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `sort_passif_picture` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
  `sort_passif_content` varchar(600) CHARACTER SET utf8 NOT NULL,
  `sort_a_name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `sort_a_picture` varchar(100) CHARACTER SET utf8 NOT NULL,
  `sort_a_content` varchar(600) CHARACTER SET utf8 NOT NULL,
  `sort_z_name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `sort_z_picture` varchar(100) CHARACTER SET utf8 NOT NULL,
  `sort_z_content` varchar(600) CHARACTER SET utf8 NOT NULL,
  `sort_e_name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `sort_e_picture` varchar(100) CHARACTER SET utf8mb4 NOT NULL,
  `sort_e_content` varchar(600) CHARACTER SET utf8 NOT NULL,
  `sort_r_name` varchar(50) CHARACTER SET utf8mb4 NOT NULL,
  `sort_r_picture` varchar(100) CHARACTER SET utf8 NOT NULL,
  `sort_r_content` varchar(600) CHARACTER SET utf8 NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `competences`
--

INSERT INTO `competences` (`id`, `sort_passif_name`, `sort_passif_picture`, `sort_passif_content`, `sort_a_name`, `sort_a_picture`, `sort_a_content`, `sort_z_name`, `sort_z_picture`, `sort_z_content`, `sort_e_name`, `sort_e_picture`, `sort_e_content`, `sort_r_name`, `sort_r_picture`, `sort_r_content`, `created_at`, `updated_at`) VALUES
(1, 'division cellulaire', 'zac/zac_sort_1.png', 'À chaque fois que Zac frappe un ennemi avec une compétence, il perd un bout de lui-même qu\'il peut absorber pour récupérer des PV. S\'il subit des dégâts mortels, Zac se divise en 4 blobs qui tentent de se recombiner. S\'il reste des blobs, Zac revient à la vie avec un nombre de PV qui dépend des PV des blobs survivants. Chaque blob a un pourcentage des PV max, de l\'armure et de la résistance magique de Zac. Cette compétence a un délai de récupération de 5 minutes.\r\n            ', 'étirements', 'zac/zac_sort_2.png', 'Zac étend un bras et attrape un ennemi. S\'il attaque ensuite un ennemi différent, il envoie les deux cibles l\'une contre l\'autre', 'matières instables', 'zac/zac_sort_3.png', 'Zac explose en direction des ennemis proches, leur infligeant des dégâts magiques équivalents à un pourcentage de leurs PV max.', 'Fronde', 'zac/zac_sort_4.png', 'Zac fixe ses bras au sol et prend de l\'élan pour se projeter vers l\'avant.', 'Boing', 'zac/zac_sort_5.png', 'Zac rebondit quatre fois, projetant en l\'air les ennemis touchés et les ralentissant.', '2020-06-07 20:11:13', NULL),
(2, 'Rage dy Berzerker', 'olaf/olaf_sort_1.png', 'La vitesse d\'attaque d\'Olaf augmente de 1% tous les 1% de PV qui lui manque.', 'Déchireuse', 'olaf/olaf_sort_2.png', 'Olaf lance sa hache à l\'endroit ciblé, infligeant des dégâts aux ennemis traversés et réduisant leur vitesse de déplacement. Si Olaf ramasse sa hache, le délai de récupération est réduit de 4,5 sec.', 'Frappes Vicieuses', 'olaf/olaf_sort_3.png', 'La vitesse d\'attaque et le Vol de vie d\'Olaf sont augmentés. Tous les soins qu\'il reçoit sont également augmentés en fonction de ses PV manquants.', 'Frappe Sauvage', 'olaf/olaf_sort_4.png', 'Olaf attaque avec tant de force qu\'il inflige des dégâts physiques bruts non seulement à sa cible, mais aussi à lui-même. Il récupère le coût en PV s\'il tue sa cible.', 'Ragnarok', 'olaf/olaf_sort_5.png', 'Olaf devient temporairement insensible aux entraves.', '2020-06-11 14:15:55', NULL),
(3, 'Rézonance', 'ekko/ekko_sort_1.png', 'La clepsydre-zéro d\'Ekko charge ses sorts et ses attaques avec de l\'énergie temporelle. Le troisième coup inflige des dégâts supplémentaires et, si la cible est un champion, Ekko reçoit un bonus en vitesse de déplacement.', 'Rétrobang', 'ekko/ekko_sort_2.png', 'Ekko lance une grenade temporelle qui crée un champ de distorsion quand elle touche un champion ennemi, ralentissant toutes les unités prises à l\'intérieur et leur infligeant des dégâts. Ensuite, la grenade se contracte et revient vers Ekko, infligeant des dégâts sur sa route.', 'Convergence parallèle', 'ekko/ekko_sort_3.png', 'Les attaques de base d\'Ekko infligent des dégâts magiques supplémentaires aux champions dont les PV sont bas. Ekko peut lancer Convergence parallèle pour fracturer la ligne temporelle, créant après quelques secondes une anomalie qui ralentit les ennemis pris à l\'intérieur. Si Ekko entre dans l\'anomalie, il obtient un bouclier et étourdit les ennemis en suspendant dans le temps leur existence.', 'Rush déphasé', 'ekko/ekko_sort_4.png', 'Ekko esquive tout en chargeant sa clepsydre-zéro. Sa prochaine attaque infligera des dégâts supplémentaires et le téléportera près de sa cible en distordant la réalité.', 'Chronofracture', 'ekko/ekko_sort_5.png', 'Ekko fracture sa ligne du temps, ce qui le rend impossible à cibler et lui permet de retourner à un moment qui lui est plus favorable. Il retourne là où il était quelques secondes plus tôt et récupère un pourcentage des PV qu\'il a perdus pendant ces quelques secondes. Les ennemis proches de sa zone d\'arrivée subissent d\'importants dégâts.', '2020-06-13 11:22:49', NULL),
(4, 'Rafale', 'leeSin/leeSin_sort_1.png', 'Après avoir utilisé une compétence, Lee Sin voit sa vitesse d\'attaque augmenter pour ses 2 prochaines attaques de base. Ces attaques accélérées lui rendent de l\'énergie.', 'Onde sonore/ coup résonant', 'leeSin/leeSin_sort_2.png', 'Onde sonore : Lee Sin émet une onde sonore pour localiser ses ennemis, infligeant des dégâts physiques au premier ennemi touché. Si Onde sonore touche un ennemi, Lee Sin peut lancer Coup résonant dans les 3 sec qui suivent. Coup résonant : Lee Sin fonce vers l\'ennemi touché par Onde sonore, infligeant des dégâts physiques en fonction des PV manquants de l\'ennemi.', 'Rempart/ Force d\'âme', 'leeSin/leeSin_sort_3.png', 'Rempart : Lee Sin fonce vers l\'allié ciblé, se protégeant contre les dégâts. Si l\'allié est un champion, il est également protégé. Après avoir lancé Rempart, Lee Sin peut lancer Force d\'âme dans les 3 sec qui suivent. Force d\'âme : l\'entraînement intense de Lee Sin lui permet de décupler ses forces pendant un combat. Pendant 4 sec, Lee Sin augmente ses effets Vol de vie et Sort vampirique.', 'Trombe / fracture', 'leeSin/leeSin_sort_4.png', 'Trombe : Lee Sin frappe le sol, envoyant une onde de choc qui inflige des dégâts magiques et révèle les unités ennemies touchées. Si Trombe touche un ennemi, Lee Sin peut lancer Fracture dans les 3 sec qui suivent. Fracture : Lee Sin estropie les ennemis proches blessés par Trombe, réduisant leur vitesse de déplacement pendant 4 sec. La vitesse de déplacement revient peu à peu à la normale pendant la durée du sort.', 'Rage du dragon', 'leeSin/leeSin_sort_5.png', 'Lee Sin donne un puissant coup de pied qui projette sa cible en arrière, infligeant des dégâts physiques à la cible et à tous les ennemis qu\'elle percute. Les ennemis ainsi percutés sont également projetés en l\'air un court instant. Cette technique lui a été enseignée par Jesse Perring, mais Lee Sin ne sait pas encore éjecter les joueurs de la carte.', '2020-06-21 13:06:24', NULL),
(5, 'Tournée', 'gragas/gragas_sort_1.png', 'Quand il utilise une compétence, Gragas boit une gorgée et récupère 6% de ses PV max. Cet effet ne peut se produire qu\'une fois toutes les 8 sec.', 'Fût roulant', 'gragas/gragas_sort_2.png', 'Gragas fait rouler son fût vers une zone ciblée ; le fût explose automatiquement au bout de 4 sec (vous pouvez activer l\'explosion manuellement). La vitesse de déplacement des ennemis touchés est réduite.', 'Rage d\'ivrogne', 'gragas/gragas_sort_3.png', 'Gragas boit pendant 1 sec. L\'ivresse qui suit le rend plus fort, ce qui lui permet d\'infliger des dégâts magiques à tous les ennemis proches avec sa prochaine attaque de base et de subir moins de dégâts.', 'Coup de bidon', 'gragas/gragas_sort_4.png', 'Gragas charge vers une zone ciblée et percute le premier ennemi rencontré, infligeant des dégâts à tous les ennemis proches et les étourdissant.', 'Fût explosif', 'gragas/gragas_sort_5.png', 'Gragas lance son fût, infligeant des dégâts et repoussant les ennemis touchés par l\'explosion.', '2020-06-21 13:58:25', NULL),
(6, 'Galop', 'hecarim/hecarim_sort_1.png', 'Les dégâts d\'attaque d\'Hecarim augmentent d\'un montant égal à un pourcentage de sa vitesse de déplacement bonus.', 'Carnage', 'hecarim/hecarim_sort_2.png', 'Hecarim tranche les ennemis proches et leur inflige des dégâts physiques. Si Hecarim blesse au moins un ennemi, il augmente les dégâts et réduit le délai de récupération des Carnages suivants.\r\n\r\n\r\n', 'Essence de la peur', 'hecarim/hecarim_sort_3.png', 'Hecarim inflige des dégâts magiques aux ennemis proches pendant un court instant. Il regagne un nombre de PV équivalent à un pourcentage de tous les dégâts subis par ces ennemis.', 'Charge dévastatrice', 'hecarim/hecarim_sort_4.png', 'La vitesse de déplacement d\'Hecarim augmente et il peut traverser les unités pendant un court instant. Sa prochaine attaque repousse la cible et inflige des dégâts physiques supplémentaires en fonction de la distance parcourue depuis l\'activation de la compétence.', 'Légion des ombres', 'hecarim/hecarim_sort_5.png', 'Hecarim invoque des cavaliers fantomatiques et charge devant lui, infligeant des dégâts magiques sur une ligne. À la fin de sa charge, Hecarim crée une onde de choc qui effraie les ennemis proches.', '2020-07-25 20:30:08', NULL),
(7, 'Tempête impitoyable', 'volibear/volibear_sort_1.png', 'Les attaques et les compétences de Volibear augmentent sa vitesse d\'attaque. Au bout d\'un moment, ses attaques de base infligent des dégâts magiques supplémentaires aux ennemis proches.', 'Coup fulgurant', 'volibear/volibear_sort_2.png', 'Volibear gagne de la vitesse en direction des ennemis, étourdissant et blessant le premier qu\'il attaque.', 'Folie Multilatrice', 'volibear/volibear_sort_3.png', 'Volibear blesse grièvement un ennemi, appliquant ses effets à l\'impact et le marquant. Relancer ce sort sur la même cible inflige des dégâts supplémentaires et soigne Volibear.', 'Foudroiement', 'volibear/volibear_sort_4.png', 'Volibear fait tomber la foudre à l\'endroit ciblé, blessant et ralentissant les ennemis tout en obtenant un bouclier s\'il est dans le rayon de l\'explosion.', 'Temête incarnée', 'volibear/volibear_sort_5.png', 'Volibear bondit vers l\'endroit ciblé, ralentissant et blessant les ennemis sous lui tout en gagnant des PV supplémentaires. Les tourelles ennemies proches de son point d\'atterrissage sont temporairement désactivées.', '2020-07-25 22:14:38', NULL),
(8, 'Ardeur Mortelle', 'pantheon/pantheon_sort_1.png', 'Après un certain nombre de sorts ou d\'attaques, le prochain sort de Pantheon est renforcé.', 'Lance Astrale', 'pantheon/pantheon_sort_2.png', 'Pantheon donne un coup de lance ou jette sa lance dans la direction choisie.', 'Assaut Martial', 'pantheon/pantheon_sort_3.png', 'Pantheon se rue sur une cible, l\'étourdissant et lui infligeant des dégâts.', 'égide impénétrable', 'pantheon/pantheon_sort_4.png', 'Pantheon lève son bouclier, devenant invulnérable aux attaques auxquelles il fait face, et donne des coups de lance en succession rapide.', 'Météore', 'pantheon/pantheon_sort_5.png', 'Pantheon rassemble ses forces pour sauter dans les airs, puis il atterrit tel un météore à l\'endroit choisi.', '2020-07-26 12:17:11', NULL),
(9, 'Titan de bric-à-brac', 'rumble/rumble_sort_1.png', 'Chaque sort lancé par Rumble augmente sa Vapeur. Quand Rumble atteint 50% de Vapeur, il entre dans la Zone rouge, ce qui confère des effets bonus à ses compétences de base. Quand il atteint 100% de Vapeur, il entre en Surchauffe, ce qui lui permet d\'infliger des dégâts supplémentaires avec ses attaques de base mais l\'empêche de lancer des sorts pendant quelques secondes.', 'Lance-flamme', 'rumble/rumble_sort_2.png', 'Rumble enflamme les adversaires devant lui, infligeant des dégâts magiques dans une zone conique pendant 3 sec. Dans la Zone rouge, les dégâts augmentent.', 'Bouclier recyclé', 'rumble/rumble_sort_3.png', 'Rumble crée un bouclier qui le protège des dégâts et lui donne un bonus de rapidité. Dans la Zone rouge, les PV du bouclier et le bonus de vitesse sont augmentés.', 'Harpon électrique', 'rumble/rumble_sort_4.png', 'Rumble tire un harpon qui électrocute sa cible, lui infligeant des dégâts magiques et réduisant sa vitesse de déplacement. Rumble peut porter 2 harpons en même temps. Dans la Zone rouge, les dégâts et le pourcentage de ralentissement sont augmentés.', 'éradication', 'rumble/rumble_sort_5.png', 'Rumble tire une bordée de roquettes, créant un mur de flammes qui blesse et ralentit les ennemis.', '2020-07-26 12:41:48', NULL),
(10, 'Protection modulable', 'camille/camille_sort_1.png', 'Les attaques de base contre les champions octroient à Camille un bouclier équivalent à 20% de ses PV max contre le type de dégâts de l\'ennemi (physique ou magique) pendant un court moment.', 'Protocole de précision', 'camille/camille_sort_2.png', 'La prochaine attaque de Camille infligera des dégâts supplémentaires et lui octroiera un bonus en vitesse de déplacement. Cette compétence peut être relancée pendant un court instant, et Camille inflige des dégâts beaucoup plus importants si elle attend entre les deux attaques.', 'Balayage tactique', 'camille/camille_sort_3.png', 'Après un délai, Camille frappe dans une zone conique, infligeant des dégâts. Les ennemis pris dans la moitié extérieure du cône sont ralentis, subissent des dégâts supplémentaires et rendent des PV à Camille.', 'Grappin', 'camille/camille_sort_4.png', 'Camille se propulse vers un mur et bondit, projetant en l\'air tous les champions ennemis à l\'atterrissage.', 'Ultimatum hextech', 'camille/camille_sort_5.png', 'Camille fonce vers le champion ciblé et l\'emprisonne dans une zone. Ses attaques de base infligent aussi des dégâts magiques supplémentaires à la cible.', '2020-07-26 13:01:33', NULL),
(11, 'Vortex des ténèbres', 'mordekaiser/mordekaiser_sort_1.png', 'Après 3 attaques ou sorts de base contre des champions, Mordekaiser gagne un puissant halo de dégâts et augmente sa vitesse de déplacement.', 'Oblitération', 'mordekaiser/mordekaiser_sort_2.png', 'Mordekaiser frappe le sol avec sa massue, infligeant des dégâts à tous les ennemis touchés. Les dégâts sont augmentés si un seul ennemi est touché.', 'Indestructible', 'mordekaiser/mordekaiser_sort_3.png', 'Mordekaiser stocke une partie des dégâts qu\'il inflige et qu\'il subit pour créer un bouclier. Il peut consommer ce bouclier pour récupérer des PV.', 'Emprise funeste', 'mordekaiser/mordekaiser_sort_4.png', 'Mordekaiser attire tous les ennemis qui se trouvent dans une zone.', 'Royaume des morts', 'mordekaiser/mordekaiser_sort_5.png', 'Mordekaiser entraîne sa victime avec lui dans une autre dimension et lui vole une partie de ses stats. S\'il la tue, il garde ces stats jusqu\'à la réapparition de sa victime.', '2020-07-26 13:35:25', NULL),
(12, 'Rage génique', 'gnar/gnar_sort_1.png', 'Gnar génère de la Rage quand il combat. Une fois sa jauge de Rage remplie, sa prochaine compétence le transforme en Méga Gnar, ce qui améliore ses défenses et lui octroie de nouvelles compétences.', 'Jet de boomerang/ jet de rocher', 'gnar/gnar_sort_2.png', 'Gnar lance un boomerang qui blesse et ralentit les cibles touchées avant de retourner vers lui. S\'il rattrape le boomerang, le délai de récupération est réduit. Méga Gnar lance un rocher qui s\'arrête à la première unité touchée, blessant et ralentissant tous les ennemis proches. Gnar peut ensuite ramasser le rocher pour réduire le délai de récupération.', 'Agitation / beigne', 'gnar/gnar_sort_3.png', 'Gnar est agité à force d\'attaquer et d\'utiliser des compétences, ce qui lui permet d\'infliger des dégâts supplémentaires et d\'augmenter sa vitesse de déplacement. Méga Gnar est enragé : il se dresse sur ses pattes arrière et frappe devant lui, étourdissant les ennemis dans la zone.', 'Rebond / Aplatissement', 'gnar/gnar_sort_4.png', 'Gnar bondit dans la direction ciblée et rebondit sur la tête de toute unité sur laquelle il atterrit, ce qui lui permet d\'aller plus loin. Méga Gnar est trop gros pour rebondir : il atterrit de façon fracassante et inflige des dégâts de zone.', 'Gnar !', 'gnar/gnar_sort_5.png', 'Méga Gnar projette tous les ennemis proches dans la direction ciblée, leur infligeant des dégâts et les ralentissant. Si un ennemi percute un mur, il est étourdi et il subit des dégâts supplémentaires.', '2020-07-26 14:00:47', NULL),
(13, 'posture du massacreur', 'aatrox/aatrox_sort_1.png', 'Régulièrement, la prochaine attaque de base d\'Aatrox inflige des dégâts physiques supplémentaires et le soigne, selon un pourcentage des PV max de la cible.', 'épée des darkin', 'aatrox/aatrox_sort_2.png', 'Aatrox abat son épée devant lui, infligeant des dégâts physiques. Il peut frapper jusqu\'à 3 fois et chaque coup a une zone d\'effet différente.', 'Chaînes infernales', 'aatrox/aatrox_sort_3.png', 'Aatrox frappe le sol, blessant le premier ennemi touché. Les champions et les grands monstres doivent vite quitter la zone d\'effet sous peine d\'être ramenés de force au point d\'impact et de subir à nouveau les dégâts.', 'Ruée obscure', 'aatrox/aatrox_sort_4.png', 'Passivement, Aatrox se soigne quand il blesse des champions ennemis. À l\'activation, il se rue dans une direction.', 'Fossoyeur des mondes', 'aatrox/aatrox_sort_5.png', 'Aatrox libère sa forme démoniaque, effrayant les sbires ennemis proches et augmentant ses dégâts d\'attaque, ses soins et sa vitesse de déplacement. La durée est prolongée s\'il participe à l\'élimination d\'un champion ennemi.', '2020-07-26 14:31:53', NULL),
(14, 'Skaarl, le lézard froussard', 'kled/kled_sort_1.png', 'Kled chevauche sa fidèle monture, Skaarl, qui subit les dégâts à sa place. Quand les PV de Skaarl tombent à zéro, Kled est désarçonné. Sans monture, les compétences de Kled changent et il inflige moins de dégâts aux champions. Kled peut restaurer le courage de Skaarl en combattant des ennemis. Quand le courage atteint son maximum, Kled se remet en selle avec une partie des PV de Skaarl.', 'Piège à ours en laisse', 'kled/kled_sort_2.png', 'Kled lance un piège à ours qui inflige des dégâts et s\'accroche à un champion ennemi. Si la cible reste accrochée pendant un court instant, elle subit des dégâts physiques supplémentaires et est tirée vers Kled. Si Kled est désarçonné, la compétence devient Pistolet de poche, un tir à distance qui projette Kled en arrière et restaure du courage.', 'Penchant pour la violence', 'kled/kled_sort_3.png', 'Kled augmente grandement sa vitesse d\'attaque le temps de quatre attaques. La quatrième attaque inflige plus de dégâts.', 'Joute', 'kled/kled_sort_4.png', 'Kled fonce dans une direction, infligeant des dégâts physiques et bénéficiant d\'un bref bonus en vitesse de déplacement. Kled peut réactiver cette compétence pour foncer en sens inverse à travers sa cible initiale, infligeant les mêmes dégâts.', 'Chaaaaaaaarger !!!', 'kled/kled_sort_5.png', 'Kled et Skaarl chargent vers la zone ciblée en s\'entourant d\'un bouclier et en laissant derrière eux une traînée qui augmente la vitesse des alliés. Skaarl fonce sur le premier champion ennemi qu\'il rencontre.', '2020-07-26 15:02:36', NULL),
(15, 'Pacte de sang', 'vladimir/vladimir_sort_1.png', 'Vladimir gagne 1 pt de puissance tous les 40 PV supplémentaires, et 1,4 PV supplémentaire tous les 1 pt de puissance (ces effets ne se cumulent pas entre eux).', 'Transfusion', 'vladimir/vladimir_sort_2.png', 'Vladimir vole les PV de l\'ennemi ciblé. Quand la jauge de ressource de Vladimir est pleine, Transfusion infligera beaucoup plus de dégâts et rendra beaucoup plus de PV pendant un court instant.', 'Bain de sang', 'vladimir/vladimir_sort_3.png', 'Vladimir plonge dans une flaque de sang, devenant impossible à cibler pendant 2 sec. Les ennemis dans la flaque sont ralentis et Vladimir peut aspirer leur vie.', 'Vagues de sang', 'vladimir/vladimir_sort_4.png', 'Vladimir dépense ses propres PV pour charger un orbe de sang qui, une fois lâché, infligera des dégâts de zone autour de lui. Les Vagues de sang peuvent être bloquées par les unités ennemies.', 'Peste sanguine', 'vladimir/vladimir_sort_5.png', 'Vladimir contamine une zone avec une peste virulente. Les ennemis infectés subissent plus de dégâts pendant la durée du sort. Après quelques secondes, Peste sanguine inflige des dégâts magiques aux ennemis infectés et rend des PV à Vladimir pour chaque champion ennemi touché.', '2020-07-26 18:29:17', NULL),
(16, 'Illumination', 'lux/lux_sort_1.png', 'Les sorts de Lux infligeant des dégâts chargent la cible en énergie pendant 6 sec. La prochaine attaque de Lux embrase l\'énergie, infligeant des dégâts magiques supplémentaires à la cible (en fonction du niveau de Lux).', 'Entrave de lumière', 'lux/lux_sort_2.png', 'Lux projette une sphère de lumière qui immobilise et blesse jusqu\'à deux unités ennemies.', 'Barrière prismatique', 'lux/lux_sort_3.png', 'Lux lance son bâton et courbe la lumière autour des cibles alliées touchées, les protégeant contre les dégâts.', 'Anomalie radieuse', 'lux/lux_sort_4.png', 'Crée une anomalie composée de lumière dans une zone, ralentissant les ennemis proches. Lux peut la faire exploser pour blesser les ennemis dans la zone d\'effet.', 'éclat final', 'lux/lux_sort_5.png', 'Après avoir chargé de l\'énergie, Lux tire un rayon lumineux qui inflige des dégâts à toutes les cibles dans la zone. En outre, Éclat final déclenche la compétence passive de Lux et rafraîchit la durée du sortilège d\'Illumination.', '2020-07-29 17:07:32', NULL),
(17, 'Mépris des faibles', 'zed/zed_sort_1.png', 'Les attaques de base de Zed infligent des dégâts magiques supplémentaires aux cibles dont les PV sont faibles. Cet effet ne peut se déclencher sur une même cible qu\'une fois toutes les quelques secondes.', 'Shuriken-rasoir', 'zed/zed_sort_2.png', 'Zed et ses ombres lancent leurs shurikens. Chaque shuriken blesse tous les ennemis touchés.', 'Ombre vivante', 'zed/zed_sort_3.png', 'Passive : Zed regagne de l\'énergie quand ses ombres et lui frappent un ennemi avec la même compétence. L\'énergie ne peut être récupérée qu\'une fois par utilisation d\'une compétence. Active : l\'ombre de Zed fonce vers l\'avant et reste sur place pendant quelques secondes. Réactiver Ombre vivante permet à Zed de changer de position avec cette ombre.', 'Taillade des ombres', 'zed/zed_sort_4.png', 'Zed et ses ombres donnent un coup de taille et blessent les ennemis proches.', 'Marque de la mort', 'zed/zed_sort_5.png', 'Zed devient impossible à cibler et fonce sur un champion ennemi pour le marquer. Au bout de 3 sec, la marque explose, infligeant de nouveau un pourcentage de tous les dégâts infligés par Zed pendant la durée de la marque.', '2020-07-31 18:08:48', NULL),
(18, 'Image miroir', 'leblanc/leblanc_sort_1.png', 'Quand LeBlanc tombe à moins de 40% de ses PV max, elle devient invisible pendant 1 sec et crée une Image miroir qui n\'inflige aucun dégât et dure jusqu\'à 8 sec. Image miroir a un délai de récupération de 1 minute. L\'Image miroir peut être contrôlée en maintenant la touche Alt et en cliquant avec le bouton droit de la souris.', 'Sceau de malveillance', 'leblanc/leblanc_sort_2.png', 'LeBlanc lance un sceau qui inflige des dégâts et qui marque la cible pendant 3,5 sec. Blesser la cible marquée avec une compétence fait exploser le sceau, infligeant des dégâts supplémentaires.', 'Distorsion', 'leblanc/leblanc_sort_3.png', 'LeBlanc fonce jusqu\'à l\'endroit visé, infligeant des dégâts aux ennemis proches de son point d\'arrivée. Dans les 4 sec qui suivent, LeBlanc peut réactiver Distorsion pour retourner à son point de départ.', 'Chaînes éthérées', 'leblanc/leblanc_sort_4.png', 'LeBlanc lance une chaîne qui s\'attache au premier ennemi touché. Si la cible reste enchaînée pendant 1,5 sec, LeBlanc l\'immobilise et lui inflige des dégâts supplémentaires.', 'Imitation', 'leblanc/leblanc_sort_5.png', 'LeBlanc imite l\'un de ses sorts de base.', '2020-07-31 18:59:10', NULL),
(19, 'Maîtrise des arcanes', 'ryze/ryze_sort_1.png', 'Les sorts de Ryze infligent des dégâts supplémentaires en fonction de son mana supplémentaire, et son mana max est augmenté d\'un pourcentage en fonction de sa puissance.', 'Court-circuit', 'ryze/ryze_sort_2.png', 'Passivement, les autres sorts de base de Ryze réinitialisent le délai de récupération de Court-circuit et chargent une rune. Lorsque Ryze lance Court-circuit avec deux runes chargées, il gagne un bref bonus en vitesse de déplacement. À l\'activation, Ryze tire une décharge de pure énergie en ligne droite, infligeant des dégâts au premier ennemi touché. Si la cible est marquée par Flux, Court-circuit inflige des dégâts supplémentaires et rebondit vers les ennemis proches marqués par Flux.', 'Prison runique', 'ryze/ryze_sort_3.png', 'Ryze piège une cible dans une prison de runes, lui infligeant des dégâts et ralentissant ses déplacements. Si la cible est marquée par Flux, elle est immobilisée au lieu d\'être ralentie.', 'Flux envoûtant', 'ryze/ryze_sort_4.png', 'Ryze projette un orbe de pure énergie magique qui blesse une cible et marque les ennemis proches de sa cible. Les sorts de Ryze ont des effets supplémentaires sur les ennemis marqués.\r\n\r\n\r\n', 'Portail transdimensionnel', 'ryze/ryze_sort_5.png', 'Passivement, Court-circuit inflige des dégâts supplémentaires aux cibles marquées par Flux. À l\'incantation, Ryze ouvre un portail menant à un endroit proche. Quelques secondes plus tard, tous les alliés près du portail sont transportés à l\'endroit ciblé.', '2020-07-31 19:16:58', NULL),
(20, 'Grâce vastaya', 'ahri/ahri_sort_1.png', 'Quand Ahri touche 2 fois un champion en peu de temps, elle augmente brièvement sa vitesse de déplacement.', 'Orbe d\'illusion', 'ahri/ahri_sort_2.png', 'Ahri lance son orbe et le ramène vers elle, infligeant des dégâts magiques à l\'aller et des dégâts bruts au retour. Après avoir touché plusieurs fois avec ses sorts, le prochain orbe qui touche des ennemis rend des PV à Ahri.', 'Lucioles', 'ahri/ahri_sort_3.png', 'Ahri libère trois lucioles qui verrouillent et attaquent les ennemis proches.', 'Charme', 'ahri/ahri_sort_4.png', 'Ahri envoie un baiser qui blesse et charme le premier ennemi qu\'il touche, interrompant immédiatement ses compétences de déplacement et le faisant marcher docilement vers elle. Ahri inflige temporairement plus de dégâts à cette cible.', 'Assaut spirituel', 'ahri/ahri_sort_4.png', 'Ahri se jette en avant et tire des traits spirituels, infligeant des dégâts aux ennemis proches. Assaut spirituel peut être lancé jusqu\'à 3 fois avant d\'entrer en phase de récupération.', '2020-07-31 19:41:03', NULL),
(21, 'Voie du vagabond', 'yasuo/yasuo_sort_1.png', 'Les chances de coup critique de Yasuo sont doublées. En outre, Yasuo génère un bouclier quand il se déplace. Le bouclier se déclenche quand un champion ou un monstre lui inflige des dégâts.', 'Tempête d\'acier', 'yasuo/yasuo_sort_2.png', 'Donne un coup d\'estoc, blessant tous les ennemis sur une ligne. À l\'impact, octroie un effet Tempête menaçante pendant quelques secondes. Après avoir cumulé 2 effets, Tempête d\'acier crée une tornade qui projette dans les airs. Tempête d\'acier est considérée comme une attaque de base et est donc renforcée par les mêmes choses.', 'Mur de vent', 'yasuo/yasuo_sort_3.png', 'Crée un mur mobile qui bloque tous les projectiles ennemis pendant 4 sec.', 'Cercle tranchant', 'yasuo/yasuo_sort_4.png', 'Traverse l\'ennemi ciblé, infligeant des dégâts magiques. Chaque utilisation augmente les dégâts de base de votre prochaine charge jusqu\'à un montant max. Ne peut pas être réutilisé sur le même ennemi pendant quelques secondes. Si Tempête d\'acier est lancée pendant une charge, elle donne un coup circulaire.', 'Dernier soupir', 'yasuo/yasuo_sort_5.png', 'Bondit sur un champion ennemi projeté dans les airs et lui inflige des dégâts physiques. En outre, tous les ennemis qui étaient projetés dans les airs dans la zone sont maintenus en l\'air. Remplit totalement l\'Impulsion mais réinitialise tous les effets cumulés de Tempête menaçante. Ensuite, pendant une durée modérée, les coups critiques de Yasuo ont une pénétration du bonus d\'armure significativement augmentée.', '2020-07-31 21:14:57', NULL),
(22, 'Ombre démonique', 'evelynn/evelynn_sort_1.png', 'En dehors des combats, Evelynn se plonge dans une Ombre démoniaque. Ombre démoniaque soigne Evelynn quand ses PV sont bas et lui octroie un camouflage à partir du niveau 6.', 'Piques de haine', 'evelynn/evelynn_sort_2.png', 'Evelynn frappe avec son cirre et inflige des dégâts à la première unité touchée. Elle peut ensuite tirer une ligne de piques vers les ennemis proches, jusqu\'à 3 fois.', 'Séduction', 'evelynn/evelynn_sort_3.png', 'Evelynn maudit une cible, ce qui permet à sa prochaine attaque ou à son prochain sort de charmer sa cible et de réduire sa résistance magique.', 'Coup de fouet', 'evelynn/evelynn_sort_4.png', 'Evelynn donne un coup de fouet à sa cible avec son cirre et lui inflige des dégâts. Elle augmente ensuite sa vitesse de déplacement pendant un court instant.', 'Faiseuse de veuves', 'evelynn/evelynn_sort_5.png', 'Evelynn devient brièvement impossible à cibler et ravage la zone devant elle avant de se téléporter loin en arrière.', '2020-08-01 18:35:36', NULL),
(23, 'Traitrîse', 'shaco/shaco_sort_1.png', 'Les attaques de base et la compétence Poison double de Shaco infligent des dégâts supplémentaires lorsqu\'elles frappent dans le dos d\'un ennemi.', 'Tromperie', 'shaco/shaco_sort_2.png', 'Shaco devient invisible et se téléporte vers la position ciblée. Sa première attaque en étant invisible est renforcée : elle inflige des dégâts supplémentaires et, si Shaco frappe dans le dos d\'un ennemi, un coup critique.', 'Boîte surprise', 'shaco/shaco_sort_3.png', 'Shaco pose une boîte cachée. Quand elle est déclenchée, elle effraie puis attaque les ennemis proches.', 'Poison double', 'shaco/shaco_sort_4.png', 'Passivement, Shaco empoisonne les cibles qu\'il touche, réduisant leur vitesse de déplacement. Shaco peut lancer son arme pour infliger des dégâts et empoisonner sa cible. Le poignard lancé inflige des dégâts supplémentaires si la cible a moins de 30% de ses PV.', 'Hallucination', 'shaco/shaco_sort_5.png', 'Shaco crée un double de lui-même à ses côtés qui peut attaquer les ennemis proches (inflige des dégâts réduits aux tourelles). En mourant, il explose, faisant apparaître trois mini-boîtes surprises et blessant les ennemis à portée.', '2020-08-01 18:55:18', NULL),
(24, 'Détermination', 'xinZhao/xin_sort_1.png', 'Toutes les 3 attaques, Xin Zhao inflige des dégâts supplémentaires et récupère des PV.', 'Frappe des trois serres', 'xinZhao/xin_sort_2.png', 'Les 3 prochaines attaques de base de Xin Zhao infligeront plus de dégâts et la 3e attaque projettera la cible dans les airs.', 'Vent et foudre', 'xinZhao/xin_sort_3.png', 'Xin Zhao donne un coup de taille devant lui avec sa lance, puis donne un coup d\'estoc, ralentissant les ennemis affectés.', 'Charge audacieuse', 'xinZhao/xin_sort_4.png', 'Xin Zhao charge un ennemi, infligeant des dégâts à tous les ennemis dans la zone et les ralentissant brièvement.', 'Garde circulaire', 'xinZhao/xin_sort_5.png', 'Xin Zhao inflige des dégâts aux ennemis proches en fonction de leurs PV actuels et repousse les cibles non défiées. Xin Zhao est immunisé contre les dégâts infligés par les champions hors du cercle créé.', '2020-08-01 19:09:35', NULL),
(25, 'Plaie béante', 'darius/darius_sort_1.png', 'Les attaques de Darius et ses compétences infligeant des dégâts font saigner les ennemis, ce qui leur inflige des dégâts physiques en 5 sec (cumulable 5 fois).', 'Décimation', 'darius/darius_sort_2.png', 'Darius tend tous ses muscles et donne un coup circulaire avec sa hache. Les ennemis touchés par la lame subissent plus de dégâts que ceux touchés par la hampe. Darius récupère des PV en fonction du nombre de champions ennemis et de grands monstres touchés par la lame.', 'Estropiaison', 'darius/darius_sort_3.png', 'La prochaine attaque de Darius tranche une artère vitale de l\'ennemi. Le saignement réduit la vitesse de déplacement de la cible.', 'Crampon', 'darius/darius_sort_4.png', 'Darius aiguise sa hache, ce qui permet à ses dégâts physiques d\'ignorer passivement un pourcentage de l\'armure de la cible. À l\'activation, Darius attire ses ennemis avec sa hache.', 'Guillotine noxienne', 'darius/darius_sort_5.png', 'Darius saute sur un champion ennemi et donne un coup fatal, infligeant des dégâts bruts. Plus vous cumulez de Plaies béantes sur la cible, plus les dégâts augmentent. Si Guillotine noxienne tue la cible, son délai de récupération est annulé pendant un court moment.', '2020-08-01 19:32:18', NULL),
(26, 'Roi de l\'arène', 'sett/sett_sort_1.png', 'Lors de ses attaques de base, Sett alterne son direct du gauche et son direct du droit. Le direct du droit est un peu plus puissant et rapide. De plus, Sett déteste perdre, ce qui augmente la régénération de ses PV selon ses PV manquants.', 'Rogne', 'sett/sett_sort_2.png', 'Les deux prochaines attaques de Sett infligent des dégâts supplémentaires en fonction des PV max de la cible. De plus, Sett augmente sa vitesse de déplacement quand il se dirige vers des champions ennemis.\r\n\r\n', 'Coup cathartique', 'sett/sett_sort_3.png', 'Passivement, Sett stocke une partie des dégâts qu\'il subit sous forme d\'agressivité. À l\'activation, Sett dépense toute l\'agressivité stockée pour gagner un bouclier et donner un coup de poing à effet de zone qui inflige des dégâts bruts au centre et des dégâts physiques sur les côtés.\r\n\r\n', 'Casse-tête', 'sett/sett_sort_4.png', 'Sett attire les ennemis venant de deux directions opposées pour leur infliger des dégâts et les étourdir. S\'il n\'y avait des ennemis que dans une direction, ces ennemis sont ralentis au lieu d\'être étourdis.', 'Le clou du spectacle', 'sett/sett_sort_5.png', 'Sett saisit un champion ennemi et l\'emporte dans les airs avant de l\'écraser au sol, infligeant des dégâts et ralentissant tous les ennemis près de son point d\'atterrissage.', '2020-08-01 19:48:00', NULL),
(27, 'Voracité', 'katarina/katarina_sort_1.png', 'Les délais de récupération des compétences de Katarina sont grandement réduits quand un champion qu\'elle a blessé récemment meurt. Si Katarina ramasse une dague, elle s\'en sert pour frapper tous les ennemis proches, infligeant des dégâts magiques.', 'Lame rebondissante', 'katarina/katarina_sort_2.png', 'Katarina lance une dague sur une cible. La dague rebondit ensuite sur les ennemis proches avant de tomber au sol.', 'Préparation', 'katarina/katarina_sort_3.png', 'Katarina augmente sa vitesse de déplacement et lance une dague dans les airs.', 'Shunpo', 'katarina/katarina_sort_4.png', 'Katarina se téléporte près de sa cible. S\'il s\'agit d\'un ennemi, elle le frappe. Sinon, elle frappe l\'ennemi le plus proche.', 'Lotus mortel', 'katarina/katarina_sort_5.png', 'Katarina tournoie et projette rapidement des couteaux sur les trois champions ennemis les plus proches, infligeant d\'énormes dégâts sur la durée de la canalisation.', '2020-08-01 22:52:13', NULL),
(28, 'Marque d\'assassin', 'akali/akali_sort_1.png', 'Blesser un champion avec une compétence crée un cercle d\'énergie autour de lui. Quitter ce cercle renforce la prochaine attaque de base d\'Akali en augmentant sa portée et ses dégâts.', 'Vague de kunais', 'akali/akali_sort_2.png', 'Akali lance cinq kunais, infligeant des dégâts selon ses dégâts d\'attaque supplémentaires et sa puissance et ralentissant les ennemis.', 'Linceul nébuleux', 'akali/akali_sort_3.png', 'Akali crée un nuage de fumée et augmente brièvement sa vitesse de déplacement. Dans ce nuage, Akali est invisible et impossible à cibler. Si elle attaque ou utilise des compétences, elle est temporairement révélée.', 'Lancer acrobatique', 'akali/akali_sort_4.png', 'Fait un salto arrière et lance un shuriken vers l\'avant, infligeant des dégâts physiques. Le premier ennemi ou nuage de fumée touché est marqué. Réactivez la compétence pour vous ruer sur la cible marquée et infliger des dégâts supplémentaires.', 'Maîtrise absolue', 'akali/akali_sort_5.png', 'Akali bondit dans une direction, blessant les ennemis qu\'elle frappe. Réactivation : Akali se rue dans une direction, exécutant tous les ennemis qu\'elle frappe.', '2020-08-01 23:31:58', NULL),
(29, 'Remontoir', 'orianna/orianna_sort_1.png', 'Les attaques de base d\'Orianna infligent des dégâts magiques supplémentaires. Plus Orianna attaque la même cible, plus les dégâts sont importants.', 'Ordre: Attaque', 'orianna/orianna_sort_2.png', 'Orianna ordonne à sa sphère de voler vers une zone cible, infligeant des dégâts magiques aux cibles sur son passage (les dégâts diminuent à chaque cible supplémentaire). La sphère reste ensuite dans la zone cible.', 'Ordre : Dissonance', 'orianna/orianna_sort_3.png', 'Orianna ordonne à sa sphère d\'émettre une impulsion énergétique, infligeant des dégâts magiques autour de la sphère. Cela crée une zone qui accélère les alliés et ralentit les ennemis.', 'Ordre : Protection', 'orianna/orianna_sort_4.png', 'Orianna ordonne à sa sphère d\'aller se fixer sur un champion allié pour le protéger, infligeant des dégâts magiques aux ennemis sur son passage. La sphère augmente l\'armure et la résistance magique du champion sur lequel elle est fixée.', 'Ordre : Onde de choc', 'orianna/orianna_sort_5.png', 'Orianna ordonne à sa sphère d\'émettre une onde de choc, infligeant des dégâts magiques et projetant les ennemis proches vers la sphère après un bref délai.', '2020-08-02 20:28:34', NULL),
(30, 'Frappe colossale', 'galio/galio_sort_1.png', 'Toutes les quelques secondes, la prochaine attaque de base de Galio inflige des dégâts magiques supplémentaires dans une zone.', 'Vents de guerre', 'galio/galio_sort_2.png', 'Galio tire deux rafales de vent qui convergent pour créer une grande tornade infligeant des dégâts sur la durée.', 'Bouclier de durand', 'galio/galio_sort_3.png', 'Galio canalise une posture défensive, ce qui ralentit ses déplacements. Au relâchement de la canalisation, Galio provoque et blesse les ennemis proches.', 'Horion de la justice', 'galio/galio_sort_4.png', 'Galio fait un pas en arrière et charge, projetant en l\'air le premier champion ennemi qu\'il touche.', 'Entrée héroïque', 'galio/galio_sort_5.png', 'Galio désigne la position d\'un allié comme zone d\'atterrissage, octroyant un bouclier anti-dégâts magiques à tous les alliés dans la zone. Après un délai, Galio s\'abat sur cet emplacement, projetant en l\'air les ennemis proches.', '2020-08-02 20:41:19', NULL),
(31, 'Plus d\'étincelles !', 'zoe/zoe_sort_1.png', 'Après avoir lancé une compétence, la prochaine attaque de base de Zoé inflige des dégâts magiques supplémentaires.', 'Astro-pong !', 'zoe/zoe_sort_2.png', 'Zoé lance un projectile qu\'elle peut rediriger en vol. Les dégâts augmentent avec la distance parcourue en ligne droite.', 'Voleuse de sorts', 'zoe/zoe_sort_3.png', 'Zoé peut ramasser les vestiges des sorts d\'invocateur et des propriétés actives d\'objets utilisés par les ennemis, puis les utiliser elle-même. Quand Zoé utilise un sort d\'invocateur, elle tire aussi trois projectiles sur l\'ennemi le plus proche.', 'Bulle soporifique', 'zoe/zoe_sort_4.png', 'La cible devient somnolente, puis s\'endort. La première attaque qui réveille la cible inflige deux fois plus de dégâts, jusqu\'à un montant max.', 'Bond dimensionnel', 'zoe/zoe_sort_5.png', 'Téléporte Zoé à un endroit proche pendant 1 sec, avant de la faire revenir à son point de départ.', '2020-08-02 20:54:23', NULL),
(32, 'Pyromanie', 'annie/annie_sort_1.png', 'Après avoir lancé 4 sorts, la prochaine compétence offensive d\'Annie étourdira sa cible.', 'Désintégration', 'annie/annie_sort_2.png', 'Annie projette une boule d\'énergie magique qui inflige des dégâts ; le coût en mana lui est rendu si l\'attaque détruit la cible.', 'Incinération', 'annie/annie_sort_3.png', 'Annie projette un cône de flammes, infligeant des dégâts à tous les ennemis dans la zone.', 'Bouclier en fusion', 'annie/annie_sort_4.png', 'Octroie à Annie un pourcentage de réduction des dégâts et un bonus en vitesse de déplacement, en plus de blesser les ennemis qui lui lancent des attaques de base.', 'Invocation : tibbers', 'annie/annie_sort_5.png', 'Annie insuffle la vie à son ours Tibbers et inflige des dégâts aux unités dans la zone d\'effet. Tibbers peut attaquer et brûle les ennemis proches de lui.', '2020-08-02 21:06:04', NULL),
(33, 'Dé pipé', 'twistedFate/twistedFate_sort_1.png', 'Quand il tue une unité, Twisted Fate lance son dé \'\'porte-bonheur\'\' et reçoit entre 1 et 6 PO supplémentaires.', 'Atouts', 'twistedFate/twistedFate_sort_2.png', 'Twisted Fate tire trois cartes qui infligent des dégâts à toutes les unités qu\'elles transpercent.', 'Bonne pioche', 'twistedFate/twistedFate_sort_3.png', 'Twisted Fate choisit une carte dans son paquet et l\'utilise pour l\'attaque suivante, gagnant des effets supplémentaires.', 'Paquet', 'twistedFate/twistedFate_sort_4.png', 'Twisted Fate inflige des dégâts supplémentaires toutes les 4 attaques. En outre, sa vitesse d\'attaque est augmentée.', 'Destinée', 'twistedFate/twistedFate_sort_5.png', 'Twisted Fate prédit le destin de ses ennemis, révélant les champions ennemis et permettant d\'utiliser Portail, ce qui téléporte Twisted Fate à un endroit de la carte en 1,5 sec.', '2020-08-09 17:56:28', NULL),
(34, 'Pierre du néant', 'kassadin/kassadin_sort_1.png', 'Kassadin absorbe 15% des dégâts magiques qu\'il subit et il peut traverser les unités.', 'Orbe du néant', 'kassadin/kassadin_sort_2.png', 'Kassadin tire un orbe d\'énergie du Néant sur sa cible, infligeant des dégâts et interrompant les canalisations. Le surplus d\'énergie lui confère un bouclier temporaire qui absorbe les dégâts magiques.', 'Lame éthérée', 'kassadin/kassadin_sort_3.png', 'Passive : les attaques de base de Kassadin infligent des dégâts magiques supplémentaires. Active : la prochaine attaque de base de Kassadin inflige d\'importants dégâts magiques supplémentaires et lui rend du mana.', 'Pulsation', 'kassadin/kassadin_sort_4.png', 'Kassadin tire de l\'énergie des sorts lancés près de lui. Après avoir tiré assez d\'énergie, Kassadin peut utiliser Pulsation pour blesser et ralentir les ennemis dans une zone en forme de cône devant lui.', 'Fissure', 'kassadin/kassadin_sort_5.png', 'Kassadin se téléporte vers une destination proche, blessant les ennemis se trouvant à proximité. Chaque utilisation de Fissure dans une courte période augmente le coût en mana et les dégâts de la Fissure suivante.', '2020-08-09 18:15:13', NULL),
(35, 'Pouvoir maléfique phénoménal', 'veigar/veigar_sort_1.png', 'Veigar est le plus grand mal qui ait jamais frappé Runeterra, et son pouvoir est encore en pleine croissance ! Frapper un champion ennemi avec un sort, tuer un champion ou effectuer une assistance octroie à Veigar un bonus permanent en puissance.', 'Coup malin', 'veigar/veigar_sort_2.png', 'Veigar lance une boule d\'énergie des ténèbres, infligeant des dégâts magiques aux deux premiers ennemis touchés. Les unités tuées par ce sort confèrent à Veigar un gain de puissance permanent.', 'Matière noire', 'veigar/veigar_sort_3.png', 'Veigar fait tomber de la matière noire pour infliger des dégâts magiques à ses adversaires. Les effets Pouvoir maléfique phénoménal cumulés réduisent le délai de récupération de Matière noire.', 'Profanation', 'veigar/veigar_sort_4.png', 'Après un bref délai, Veigar distord les confins de l\'espace autour de la cible pendant 3 secondes, étourdissant les ennemis qui traversent le périmètre.', 'Explosion primordiale', 'veigar/veigar_sort_5.png', 'Lance de l\'énergie explosive sur le champion ennemi ciblé, infligeant d\'importants dégâts magiques qui augmentent avec les PV manquants de la cible.', '2020-08-09 18:26:06', NULL),
(36, 'munitions hextech', 'corki/corki_sort_1.png', 'Les attaques de base de Corki infligent un pourcentage de leurs dégâts physiques sous forme de dégâts magiques. Régulièrement, le Paquet est déposé dans la base de Corki. Si celui-ci le récupère, il reçoit un bonus en vitesse de déplacement en dehors des combats et améliore Valkyrie en Livraison spéciale.', 'Bombe au phosphore', 'corki/corki_sort_2.png', 'Corki tire une bombe éclairante à l\'endroit visé, infligeant des dégâts magiques aux ennemis dans la zone. Cette attaque révèle pendant un temps les unités dans la zone.', 'Valkyrie', 'corki/corki_sort_3.png', 'Corki franchit une courte distance, lâchant des bombes et créant une traînée de feu qui inflige des dégâts aux ennemis.', 'gatling', 'corki/corki_sort_4.png', 'La mitrailleuse de Corki tire rapidement dans une zone conique face à lui, infligeant des dégâts et réduisant l\'armure et la résistance magique de l\'ennemi.', 'Barrage de projectiles', 'corki/corki_sort_5.png', 'Corki tire un projectile dans une direction. Il explose à l\'impact et inflige des dégâts aux ennemis dans la zone. Corki stocke des projectiles sur la durée, jusqu\'à un maximum donné. Un projectile sur 3 est une grosse Bertha qui inflige plus de dégâts.', '2020-08-10 08:56:54', NULL),
(37, 'Combattant agile', 'fizz/fizz_sort_1.png', 'Fizz peut traverser les unités et profite d\'un montant fixe de réduction des dégâts contre toutes les sources de dégâts.', 'Frappe de l\'oursin', 'fizz/fizz_sort_2.png', 'Fizz traverse sa cible, infligeant des dégâts magiques et des effets à l\'impact.', 'Trident marin', 'fizz/fizz_sort_3.png', 'Les attaques de Fizz font saigner ses ennemis, infligeant des dégâts magiques en plusieurs secondes. Fizz peut renforcer sa prochaine attaque pour infliger des dégâts supplémentaires, et renforcer ses attaques suivantes pour une courte durée.', 'Joueur/filou', 'fizz/fizz_sort_4.png', 'Fizz saute et retombe avec grâce sur sa lance, devenant impossible à cibler. Depuis cette position, Fizz peut soit frapper le sol, soit sauter à nouveau avant de retomber.', 'Pêche au gros', 'fizz/fizz_sort_5.png', 'Fizz lance un poisson qui s\'accroche à tout champion qui le touche, ralentissant la cible. Après un court instant, un requin surgit du sol, projetant la cible dans les airs et repoussant les ennemis proches. Tous les ennemis touchés subissent des dégâts magiques et sont ralentis.', '2020-08-10 16:08:57', NULL),
(38, 'Voie du chasseur', 'yone/yone_sort_1.png', 'Une attaque de Yone sur deux inflige des dégâts magiques. De plus, ses chances de coup critique sont doublées.', 'Acier Mortel', 'yone/yone_sort_2.png', 'Donne un coup d\'estoc, blessant tous les ennemis sur une ligne. À l\'impact, octroie un effet Tempête menaçante pendant quelques secondes. À 2 effets cumulés, Acier mortel permet à Yone de se ruer vers l\'avant dans une rafale de vent qui projette les ennemis dans les airs. Acier mortel est considéré comme une attaque de base et est donc renforcé par les mêmes choses.', 'Fendoir Spirituel', 'yone/yone_sort_3.png', 'Yone frappe devant lui en blessant tous les ennemis dans une zone conique. Yone obtient un bouclier dont les PV augmentent avec le nombre de champions touchés. Les délais de récupération et d\'incantation de Fendoir spirituel sont réduits par la vitesse d\'attaque.', 'Libération spirituelle', 'yone/yone_sort_4.png', 'L\'esprit de Yone quitte son corps et gagne en vitesse de déplacement. Quand cette compétence prend fin, Yone est renvoyé de force dans son corps et une partie des dégâts qu\'il a infligés sous forme d\'esprit est répétée.', 'Destin Scellé', 'yone/yone_sort_5.png', 'Yone se téléporte derrière le dernier champion sur une ligne en donnant un coup si puissant qu\'il attire vers lui tous les ennemis touchés.', '2020-09-07 18:39:14', NULL);

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `competences`
--
ALTER TABLE `competences`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `competences`
--
ALTER TABLE `competences`
  MODIFY `id` int(255) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
